apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: techchallenge-backend
  name: techchallenge-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: techchallenge.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: techchallenge-backend
            port:
              number: 8080